- name: Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  vars_files:
    - just-vars.yml
  tasks:
    - name: Print a variable
      vars:
        URL: task.google.com
      ansible.module.debug:
        msg: var URL is {{ URL }}
    - name: Print a variable
      ansible.module.debug:
        msg: var URL is {{ URL }}

  roles:
    - sample
