- name: Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: Print a variable
      vars:
        URL: task.google.com
      ansible.module.debug:
        msg: var URL is {{ URL }}
    - name: Print a variable
      ansible.module.debug:
        msg: var URL is {{ URL }}
